name: Publish NuGet tool

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.x
        
    - name: Restore dependencies
      run: dotnet restore
      
#    - name: Run Tests
#      run: dotnet test --verbosity normal
      
    - name: Build package
      run: dotnet pack ./src/RoslynMcp.Host/RoslynMcp.Host.csproj --output .nupkg
      
    - name: Add GitHub Packages source
      run: dotnet nuget add source \
        --username ${{ github.actor }} \
        --password ${{ secrets.GITHUB_TOKEN }} \
        --store-password-in-clear-text \
        --name github \
        "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Publish package
      working-directory: ./.nupkg 
      run: dotnet nuget push **/*.nupkg \
        --source github \
        --api-key ${{ secrets.GITHUB_TOKEN }} \
        --skip-duplicate
